language: go
os: linux
sudo: require
dist: trusty

go:
  - 1.7.1
go_import_path: github.com/hasura/minikube

install:
  - sudo apt-get -qqy install libvirt-dev
script:
  - make test
after_success:
  - bash <(curl -s https://codecov.io/bash)
