language: go
os: linux

go:
  - 1.8.3
go_import_path: github.com/hasura/hasuractl/pkg/minikube

install:
  - echo "Don't run anything."
script:
  - make test
after_success:
  - bash <(curl -s https://codecov.io/bash)
